server:
  port: 8085
database:
  connection: mongodb://localhost:27017/bigScreen
facebook:
  appId: '538291453008493'
  secret: '4987654a1357b15f1eda1e4bf770769a'
  validateToken: 'https://graph.facebook.com/app?access_token='
  userInfo: 'https://graph.facebook.com/me?fields=name,email,first_name,last_name,picture&access_token='
user:
   storePhotoPath: 'public/img/users/{{id}}'
   webPhotoPath: 'img/users/{{id}}/profile.png'
