server:
  port: 8888
index:
  projector: 'index-projector.html'
  mobile: 'index.html'
database:
  connection: mongodb://localhost:27017/bigScreen
user:
   storePhotoPath: 'public/img/users/{{id}}'
   webPhotoPath: 'img/users/{{id}}/profile.png'
